### ISSUE TITLE
failed to build with rustc 1.21.0-nightly (1d2a6df38 2017-08-03)

### ISSUE THREAD

**Issue by alsam** [ReTeX/ReX#31]
Hello Developers,

_ReX_  at `69593e240f10f3976ea4a86c1243678483c2de03` failed to build with
rustc 1.21.0-nightly (1d2a6df38 2017-08-03)
```sh
   Compiling rex v0.1.0 (file:///scratch/github/ReX)
error: unexpected end of macro invocation
   --> src/layout/engine.rs:578:17
    |
578 |         contents,
    |                 ^

error: Could not compile `rex`.
```
Thanks

**Comment by alsam** [comment]
fix was trivial, just removed comma at the end of `contents,`

**Comment by cbreeden** [comment]
Hi, sorry for the late response.  The notification must have gotten lost in my email, and to be honest, I haven't been looking out for issues.  Unfortunately, I am not able to reproduce the issue (it's strange that travis-ci passed tests on that commit).

Unfortunately, the README is a little out of date.  Currently, I have been running this command to test (use any formula you'd like instead):
```bash
cargo run --bin qc 'x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}'
```  
This generates a `test.svg` in the current directory with the rendering.  You will need the `rex-xits.otf` font in the local directory as well. I don't have anything written to make it more user friendly.  But please let me know if you find any bugs, it would be appreciated.

**Comment by alsam** [comment]
Hi, thank you for response and for expanding on how to run the tool.
You tool is great as it is self-sufficient and doesn't require external dependencies such as TeX/LaTeX. Weird I am not able to reproduce the issue, guess it was `rustfmt` bug.
So close the issue as irreproducible.
